language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
cache:
  directories:
  - $HOME/.m2
script:
  - mvn -U install -Dmaven.test.skip=true -Dfindbugs.skip=true
  - mvn test

